# Generated by Django 4.2.23 on 2025-06-13 16:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsOnCApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='provider_img', to='WhatsOnCApp.provider'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_img', to='WhatsOnCApp.event')),
            ],
        ),
    ]
