# Generated by Django 4.2.23 on 2025-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsOnCApp', '0002_image_provider_imageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='appproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='provider',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
