# Generated by Django 4.2.23 on 2025-07-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsOnCApp', '0005_provider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_img', to='WhatsOnCApp.event'),
        ),
    ]
