# Generated by Django 4.2.23 on 2025-07-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsOnCApp', '0007_alter_imageevent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('provider', 'About a provider'), ('event', 'About an event'), ('enquiry', 'General enquiry'), ('claim or complain', 'Claim or Complain')], max_length=30)),
                ('description', models.TextField(max_length=800)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
