# Generated by Django 4.2.23 on 2025-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsOnCApp', '0008_contactus_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
