# Generated by Django 4.2.23 on 2025-07-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
