# Generated by Django 4.2.23 on 2025-07-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityApp', '0002_remove_userprofile_role_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
